import Head from 'next/head'
import Message from "../components/message";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <div className="ny-12 text-lg font-medium">
             <h2>See what people are saying</h2>
            <Message/>
            <Message/>
        </div>
    </div>
  )
}
